"""Scan benchmark artifacts and submission files for credential material.

The scanner reports file names and pattern *kinds* only. It never prints the
matched value, which makes it suitable for a final read-only check over Harbor
reports, traces, logs, PNGs, and the submission archive itself.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import zipfile
from collections.abc import Iterable, Mapping, Sequence
from pathlib import Path
from typing import Any

# Support both ``python -m scripts.scan_credentials`` and the documented
# ``python scripts/scan_credentials.py`` form.  In the latter case Python puts
# only the ``scripts`` directory on ``sys.path``, so the namespace package name
# is not importable even though the sibling module is available.
try:
    from scripts.build_submission import _known_secrets
except ModuleNotFoundError as exc:
    if exc.name != "scripts":
        raise
    from build_submission import _known_secrets

_TOKEN_PATTERN = re.compile(
    rb"(?:sk-[A-Za-z0-9_-]{16,}|Bearer\s+[A-Za-z0-9._~+/=-]{12,})"
)


def _safe_path(path: Path, secrets: Sequence[bytes]) -> str:
    value = str(path)
    encoded = value.encode("utf-8", errors="replace")
    for secret in secrets:
        if secret:
            encoded = encoded.replace(secret, b"[REDACTED]")
    return encoded.decode("utf-8", errors="replace")


def _patterns(data: bytes, secrets: Sequence[bytes]) -> tuple[str, ...]:
    found: list[str] = []
    if any(secret and secret in data for secret in secrets):
        found.append("known_secret")
    if _TOKEN_PATTERN.search(data):
        found.append("token_pattern")
    return tuple(found)


def _iter_files(paths: Iterable[Path]) -> Iterable[Path]:
    for root in paths:
        if root.is_file():
            # A caller that names one file explicitly gets that file scanned,
            # even when it is a generated bytecode file.  Cache pruning below
            # applies only while recursively walking a directory.
            yield root
            continue
        if not root.is_dir():
            continue
        try:
            candidates = sorted(
                item
                for item in root.rglob("*")
                if item.is_file()
                and "__pycache__" not in item.parts
                and item.suffix not in {".pyc", ".pyo"}
            )
        except OSError:
            continue
        yield from candidates


def scan_file(path: Path, *, secrets: Sequence[bytes] = ()) -> dict[str, Any]:
    """Scan one file and return a value-free finding record."""

    try:
        data = path.read_bytes()
    except (OSError, UnicodeError) as exc:
        return {
            "path": _safe_path(path, secrets),
            "status": "error",
            "error_type": type(exc).__name__,
        }

    findings = list(_patterns(data, secrets))
    if zipfile.is_zipfile(path):
        try:
            with zipfile.ZipFile(path) as archive:
                for member in archive.infolist():
                    if member.is_dir():
                        continue
                    try:
                        member_data = archive.read(member)
                    except (OSError, KeyError, RuntimeError, zipfile.BadZipFile):
                        findings.append("archive_read_error")
                        continue
                    findings.extend(
                        f"archive:{kind}" for kind in _patterns(member_data, secrets)
                    )
        except (OSError, zipfile.BadZipFile):
            findings.append("archive_read_error")

    unique_findings = tuple(dict.fromkeys(findings))
    return {
        "path": _safe_path(path, secrets),
        "status": "finding" if unique_findings else "clean",
        "patterns": list(unique_findings),
    }


def scan_paths(
    paths: Iterable[str | os.PathLike[str]],
    *,
    environ: Mapping[str, str] | None = None,
) -> dict[str, Any]:
    """Scan files/directories recursively without exposing secret values."""

    secret_values = _known_secrets(dict(os.environ if environ is None else environ))
    secret_bytes = tuple(secret_values)
    roots = tuple(Path(item).expanduser().resolve(strict=False) for item in paths)
    records = [scan_file(path, secrets=secret_bytes) for path in _iter_files(roots)]
    findings = [record for record in records if record.get("status") == "finding"]
    errors = [record for record in records if record.get("status") == "error"]
    return {
        "schema_version": "credential-scan/v1",
        "scanned_files": len(records),
        "finding_count": len(findings),
        "error_count": len(errors),
        "clean": not findings and not errors,
        "records": records,
    }


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("paths", nargs="+", type=Path)
    parser.add_argument("--json", action="store_true", dest="as_json")
    arguments = parser.parse_args(argv)
    report = scan_paths(arguments.paths)
    if arguments.as_json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        print(
            f"scanned={report['scanned_files']} findings={report['finding_count']} "
            f"errors={report['error_count']}"
        )
        for record in report["records"]:
            if record.get("status") != "clean":
                print(f"{record.get('status')}: {record.get('path')}")
    return 1 if report["finding_count"] or report["error_count"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
